/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 ./public/Pogoblender.glb 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Model(props) {
  const group = React.useRef()
  const { scene } = useGLTF('/Pogoblender.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials, animations } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="ground" geometry={nodes.ground.geometry} material={nodes.ground.material} position={[5, 0.5, 5]} />
        <mesh name="helmet" geometry={nodes.helmet.geometry} material={nodes.helmet.material} position={[4.054, 0.702, 5.059]} rotation={[-0.279, 0, 0]} scale={2.35} />
        <mesh name="pogo_1" geometry={nodes.pogo_1.geometry} material={nodes.pogo_1.material} position={[4.089, 0.702, 5.059]}>
          <group name="armature_template001" position={[-0.043, 3.643, -0.675]} scale={3.774}>
            <primitive object={nodes.Bone11} />
            <primitive object={nodes.poleL} />
            <primitive object={nodes.Bone029L} />
            <primitive object={nodes.poleR} />
            <primitive object={nodes.Bone029R} />
            <skinnedMesh name="newbody" geometry={nodes.newbody.geometry} material={nodes.newbody.material} skeleton={nodes.newbody.skeleton} />
          </group>
          <mesh name="led" geometry={nodes.led.geometry} material={nodes.led.material} position={[0.028, 9.969, -0.007]} />
        </mesh>
        <mesh name="ground_2" geometry={nodes.ground_2.geometry} material={nodes.ground_2.material} position={[400, 0, -20]} />
        <mesh name="ground_3" geometry={nodes.ground_3.geometry} material={nodes.ground_3.material} position={[0, 0, -20]} />
        <mesh name="wheel" geometry={nodes.wheel.geometry} material={nodes.wheel.material} position={[-2.295, 59.378, 141.182]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="jumpx2icon" geometry={nodes.jumpx2icon.geometry} material={nodes.jumpx2icon.material} position={[-21.522, 4.519, 5.477]} />
        <mesh name="coin" geometry={nodes.coin.geometry} material={nodes.coin.material} position={[7.347, 10.285, 5.334]} rotation={[Math.PI / 2, 0, 0]} />
        <mesh name="jumpicon" geometry={nodes.jumpicon.geometry} material={nodes.jumpicon.material} position={[-32.622, 5.94, 5.5]} />
        <mesh name="speedicon" geometry={nodes.speedicon.geometry} material={nodes.speedicon.material} position={[-32.691, 4.04, 0.894]} />
        <mesh name="cylinder_2" geometry={nodes.cylinder_2.geometry} material={nodes.cylinder_2.material} position={[5.053, 0.958, -4.495]}>
          <mesh name="cylinder_2001" geometry={nodes.cylinder_2001.geometry} material={nodes.cylinder_2001.material} />
          <mesh name="cylinder_2002" geometry={nodes.cylinder_2002.geometry} material={nodes.cylinder_2002.material} />
          <mesh name="cylinder_2003" geometry={nodes.cylinder_2003.geometry} material={nodes.cylinder_2003.material} />
          <mesh name="cylinder_2004" geometry={nodes.cylinder_2004.geometry} material={nodes.cylinder_2004.material} />
          <mesh name="cylinder_2005" geometry={nodes.cylinder_2005.geometry} material={nodes.cylinder_2005.material} />
          <mesh name="cylinder_2006" geometry={nodes.cylinder_2006.geometry} material={nodes.cylinder_2006.material} />
          <mesh name="cylinder_2007" geometry={nodes.cylinder_2007.geometry} material={nodes.cylinder_2007.material} />
          <mesh name="cylinder_2008" geometry={nodes.cylinder_2008.geometry} material={nodes.cylinder_2008.material} />
          <mesh name="cylinder_2009" geometry={nodes.cylinder_2009.geometry} material={nodes.cylinder_2009.material} />
          <mesh name="cylinder_2010" geometry={nodes.cylinder_2010.geometry} material={nodes.cylinder_2010.material} />
          <mesh name="cylinder_2011" geometry={nodes.cylinder_2011.geometry} material={nodes.cylinder_2011.material} />
          <mesh name="cylinder_2012" geometry={nodes.cylinder_2012.geometry} material={nodes.cylinder_2012.material} />
          <mesh name="cylinder_2013" geometry={nodes.cylinder_2013.geometry} material={nodes.cylinder_2013.material} />
          <mesh name="cylinder_2014" geometry={nodes.cylinder_2014.geometry} material={nodes.cylinder_2014.material} />
          <mesh name="cylinder_2015" geometry={nodes.cylinder_2015.geometry} material={nodes.cylinder_2015.material} />
          <mesh name="cylinder_2016" geometry={nodes.cylinder_2016.geometry} material={nodes.cylinder_2016.material} />
          <mesh name="cylinder_2017" geometry={nodes.cylinder_2017.geometry} material={nodes.cylinder_2017.material} />
          <mesh name="cylinder_2018" geometry={nodes.cylinder_2018.geometry} material={nodes.cylinder_2018.material} />
          <mesh name="cylinder_2019" geometry={nodes.cylinder_2019.geometry} material={nodes.cylinder_2019.material} />
          <mesh name="cylinder_2020" geometry={nodes.cylinder_2020.geometry} material={nodes.cylinder_2020.material} />
          <mesh name="cylinder_2021" geometry={nodes.cylinder_2021.geometry} material={nodes.cylinder_2021.material} />
          <mesh name="cylinder_2022" geometry={nodes.cylinder_2022.geometry} material={nodes.cylinder_2022.material} />
          <mesh name="cylinder_2023" geometry={nodes.cylinder_2023.geometry} material={nodes.cylinder_2023.material} />
          <mesh name="cylinder_2024" geometry={nodes.cylinder_2024.geometry} material={nodes.cylinder_2024.material} />
        </mesh>
        <mesh name="cube_1" geometry={nodes.cube_1.geometry} material={nodes.cube_1.material} position={[16.832, 0.883, -3.199]}>
          <mesh name="cube_1001" geometry={nodes.cube_1001.geometry} material={nodes.cube_1001.material} />
          <mesh name="cube_1002" geometry={nodes.cube_1002.geometry} material={nodes.cube_1002.material} />
          <mesh name="cube_1003" geometry={nodes.cube_1003.geometry} material={nodes.cube_1003.material} />
          <mesh name="cube_1004" geometry={nodes.cube_1004.geometry} material={nodes.cube_1004.material} />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/Pogoblender.glb')
